from __future__ import annotations

from app.core.exceptions import UnsupportedTimeframeError


SUPPORTED_TIMEFRAMES = ("1d", "4h", "1h", "15m", "3m")
TIMEFRAME_TO_MINUTES = {"1d": 1440, "4h": 240, "1h": 60, "15m": 15, "3m": 3}
MAINLINE_STRATEGY_PROFILE = "swing_trend_long_regime_gate_v1"
WORKSPACE_BATCH_PROFILES = ("swing_trend_long_regime_gate_v1", "intraday_mtf_v1")
LEGACY_STRATEGY_PROFILES = (
    "trend_pullback_v1",
    "swing_trend_v1",
    "intraday_mtf_v1",
)
RESEARCH_STRATEGY_PROFILES = (
    "swing_trend_axis_band_diagnostic_v1",
    "swing_trend_axis_band_risk_overlay_v1",
    "swing_trend_axis_band_state_note_v1",
    "swing_trend_confluence_setup_v1",
    "swing_trend_confluence_min_hits_3_v1",
    "swing_trend_confluence_max_spread_10_v1",
    "swing_trend_structure_gate_hard_v1",
    "swing_trend_confluence_structure_gate_hard_v1",
    "swing_trend_level_aware_confirmation_v1",
    "swing_trend_level_aware_confirmation_min_hits_2_v1",
    "swing_trend_level_aware_confirmation_ema55_025_v1",
    "swing_trend_level_aware_confirmation_band_touch_035_v1",
    "swing_trend_matrix_no_gate_current_entry_v1",
    "swing_trend_matrix_gate_simple_entry_v1",
    "swing_trend_matrix_no_gate_simple_entry_v1",
    "swing_breakout_v1_btc",
    "swing_breakout_setup_proximity_045_v1_btc",
    "swing_breakout_trigger_buffer_004_v1_btc",
    "swing_breakout_base_width_45_v1_btc",
    "swing_range_failure_v1_btc",
    "swing_range_failure_edge_035_v1_btc",
    "swing_range_failure_sweep_008_v1_btc",
    "swing_range_failure_max_width_45_v1_btc",
    "swing_exhaustion_divergence_ct_block80_v1_btc",
    "swing_exhaustion_divergence_min_level3_v1_btc",
    "swing_exhaustion_divergence_v1_btc",
    "swing_exhaustion_divergence_short_only_v1_btc",
    "swing_neutral_range_reversion_v1_btc",
    "swing_neutral_range_reversion_edge_030_v1_btc",
    "swing_neutral_range_reversion_sweep_008_v1_btc",
    "swing_neutral_range_reversion_opp_r_100_v1_btc",
    "swing_trend_divergence_v1",
    "swing_trend_divergence_min_level3_v1",
    "swing_trend_divergence_no_reversal_v1",
    "swing_trend_long_divergence_gate_v1",
    "swing_trend_long_regime_short_relaxed_trigger_v1",
    "swing_trend_long_regime_short90_free_space_v1",
    "swing_trend_long_regime_short_no_auxiliary_v1",
    "swing_trend_long_regime_short_no_reversal_v1",
    "swing_trend_long_regime_short_no_reversal_no_aux_v1",
    "swing_trend_ablation_no_reversal_v1",
    "swing_trend_ablation_symmetric_regime_v1",
    "swing_trend_ablation_no_regained_fast_v1",
    "swing_trend_ablation_no_held_slow_v1",
    "swing_trend_ablation_no_auxiliary_v1",
    "swing_trend_ablation_minimal_trigger_v1",
    "swing_trend_simple_candidate_v1",
    "swing_trend_simple_candidate_v2",
    "trend_pullback_pullback_085_v1",
    "trend_pullback_trend70_v1",
    "trend_pullback_aux2_v1",
    "intraday_mtf_v2",
    "intraday_mtf_v2_pullback_075_v1",
    "intraday_mtf_v2_trend70_v1",
    "intraday_mtf_v2_cooldown10_v1",
)
SUPPORTED_STRATEGY_PROFILES = (
    "trend_pullback_v1",
    "trend_pullback_pullback_085_v1",
    "trend_pullback_trend70_v1",
    "trend_pullback_aux2_v1",
    "swing_trend_v1",
    "swing_breakout_v1_btc",
    "swing_breakout_setup_proximity_045_v1_btc",
    "swing_breakout_trigger_buffer_004_v1_btc",
    "swing_breakout_base_width_45_v1_btc",
    "swing_range_failure_v1_btc",
    "swing_range_failure_edge_035_v1_btc",
    "swing_range_failure_sweep_008_v1_btc",
    "swing_range_failure_max_width_45_v1_btc",
    "swing_exhaustion_divergence_ct_block80_v1_btc",
    "swing_exhaustion_divergence_min_level3_v1_btc",
    "swing_exhaustion_divergence_v1_btc",
    "swing_exhaustion_divergence_short_only_v1_btc",
    "swing_neutral_range_reversion_v1_btc",
    "swing_neutral_range_reversion_edge_030_v1_btc",
    "swing_neutral_range_reversion_sweep_008_v1_btc",
    "swing_neutral_range_reversion_opp_r_100_v1_btc",
    "swing_trend_divergence_v1",
    "swing_trend_divergence_min_level3_v1",
    "swing_trend_divergence_no_reversal_v1",
    "swing_trend_long_divergence_gate_v1",
    "swing_trend_long_regime_gate_v1",
    "swing_trend_axis_band_diagnostic_v1",
    "swing_trend_axis_band_risk_overlay_v1",
    "swing_trend_axis_band_state_note_v1",
    "swing_trend_confluence_setup_v1",
    "swing_trend_confluence_min_hits_3_v1",
    "swing_trend_confluence_max_spread_10_v1",
    "swing_trend_structure_gate_hard_v1",
    "swing_trend_confluence_structure_gate_hard_v1",
    "swing_trend_level_aware_confirmation_v1",
    "swing_trend_level_aware_confirmation_min_hits_2_v1",
    "swing_trend_level_aware_confirmation_ema55_025_v1",
    "swing_trend_level_aware_confirmation_band_touch_035_v1",
    "swing_trend_matrix_no_gate_current_entry_v1",
    "swing_trend_matrix_gate_simple_entry_v1",
    "swing_trend_matrix_no_gate_simple_entry_v1",
    "swing_trend_long_regime_short_relaxed_trigger_v1",
    "swing_trend_long_regime_short90_free_space_v1",
    "swing_trend_long_regime_short_no_auxiliary_v1",
    "swing_trend_long_regime_short_no_reversal_v1",
    "swing_trend_long_regime_short_no_reversal_no_aux_v1",
    "swing_trend_ablation_no_reversal_v1",
    "swing_trend_ablation_symmetric_regime_v1",
    "swing_trend_ablation_no_regained_fast_v1",
    "swing_trend_ablation_no_held_slow_v1",
    "swing_trend_ablation_no_auxiliary_v1",
    "swing_trend_ablation_minimal_trigger_v1",
    "swing_trend_simple_candidate_v1",
    "swing_trend_simple_candidate_v2",
    "intraday_mtf_v1",
    "intraday_mtf_v2",
    "intraday_mtf_v2_pullback_075_v1",
    "intraday_mtf_v2_trend70_v1",
    "intraday_mtf_v2_cooldown10_v1",
)
STRATEGY_REQUIRED_TIMEFRAMES = {
    "trend_pullback_v1": ("1d", "4h", "1h", "15m"),
    "trend_pullback_pullback_085_v1": ("1d", "4h", "1h", "15m"),
    "trend_pullback_trend70_v1": ("1d", "4h", "1h", "15m"),
    "trend_pullback_aux2_v1": ("1d", "4h", "1h", "15m"),
    "swing_trend_v1": ("1d", "4h", "1h"),
    "swing_breakout_v1_btc": ("1d", "4h", "1h"),
    "swing_breakout_setup_proximity_045_v1_btc": ("1d", "4h", "1h"),
    "swing_breakout_trigger_buffer_004_v1_btc": ("1d", "4h", "1h"),
    "swing_breakout_base_width_45_v1_btc": ("1d", "4h", "1h"),
    "swing_range_failure_v1_btc": ("1d", "4h", "1h"),
    "swing_range_failure_edge_035_v1_btc": ("1d", "4h", "1h"),
    "swing_range_failure_sweep_008_v1_btc": ("1d", "4h", "1h"),
    "swing_range_failure_max_width_45_v1_btc": ("1d", "4h", "1h"),
    "swing_exhaustion_divergence_ct_block80_v1_btc": ("1d", "4h", "1h"),
    "swing_exhaustion_divergence_min_level3_v1_btc": ("1d", "4h", "1h"),
    "swing_exhaustion_divergence_v1_btc": ("1d", "4h", "1h"),
    "swing_exhaustion_divergence_short_only_v1_btc": ("1d", "4h", "1h"),
    "swing_neutral_range_reversion_v1_btc": ("1d", "4h", "1h"),
    "swing_neutral_range_reversion_edge_030_v1_btc": ("1d", "4h", "1h"),
    "swing_neutral_range_reversion_sweep_008_v1_btc": ("1d", "4h", "1h"),
    "swing_neutral_range_reversion_opp_r_100_v1_btc": ("1d", "4h", "1h"),
    "swing_trend_divergence_v1": ("1d", "4h", "1h"),
    "swing_trend_divergence_min_level3_v1": ("1d", "4h", "1h"),
    "swing_trend_divergence_no_reversal_v1": ("1d", "4h", "1h"),
    "swing_trend_long_divergence_gate_v1": ("1d", "4h", "1h"),
    "swing_trend_long_regime_gate_v1": ("1d", "4h", "1h"),
    "swing_trend_axis_band_diagnostic_v1": ("1d", "4h", "1h"),
    "swing_trend_axis_band_risk_overlay_v1": ("1d", "4h", "1h"),
    "swing_trend_axis_band_state_note_v1": ("1d", "4h", "1h"),
    "swing_trend_confluence_setup_v1": ("1d", "4h", "1h"),
    "swing_trend_confluence_min_hits_3_v1": ("1d", "4h", "1h"),
    "swing_trend_confluence_max_spread_10_v1": ("1d", "4h", "1h"),
    "swing_trend_structure_gate_hard_v1": ("1d", "4h", "1h"),
    "swing_trend_confluence_structure_gate_hard_v1": ("1d", "4h", "1h"),
    "swing_trend_level_aware_confirmation_v1": ("1d", "4h", "1h"),
    "swing_trend_level_aware_confirmation_min_hits_2_v1": ("1d", "4h", "1h"),
    "swing_trend_level_aware_confirmation_ema55_025_v1": ("1d", "4h", "1h"),
    "swing_trend_level_aware_confirmation_band_touch_035_v1": ("1d", "4h", "1h"),
    "swing_trend_matrix_no_gate_current_entry_v1": ("1d", "4h", "1h"),
    "swing_trend_matrix_gate_simple_entry_v1": ("1d", "4h", "1h"),
    "swing_trend_matrix_no_gate_simple_entry_v1": ("1d", "4h", "1h"),
    "swing_trend_long_regime_short_relaxed_trigger_v1": ("1d", "4h", "1h"),
    "swing_trend_long_regime_short90_free_space_v1": ("1d", "4h", "1h"),
    "swing_trend_long_regime_short_no_auxiliary_v1": ("1d", "4h", "1h"),
    "swing_trend_long_regime_short_no_reversal_v1": ("1d", "4h", "1h"),
    "swing_trend_long_regime_short_no_reversal_no_aux_v1": ("1d", "4h", "1h"),
    "swing_trend_ablation_no_reversal_v1": ("1d", "4h", "1h"),
    "swing_trend_ablation_symmetric_regime_v1": ("1d", "4h", "1h"),
    "swing_trend_ablation_no_regained_fast_v1": ("1d", "4h", "1h"),
    "swing_trend_ablation_no_held_slow_v1": ("1d", "4h", "1h"),
    "swing_trend_ablation_no_auxiliary_v1": ("1d", "4h", "1h"),
    "swing_trend_ablation_minimal_trigger_v1": ("1d", "4h", "1h"),
    "swing_trend_simple_candidate_v1": ("1d", "4h", "1h"),
    "swing_trend_simple_candidate_v2": ("1d", "4h", "1h"),
    "trend_following_v1": ("1d", "4h", "1h"),
    "swing_improved_v1": ("1d", "4h", "1h"),
    "mean_reversion_v1": ("1d", "4h", "1h"),
    "intraday_mtf_v1": ("1h", "15m", "3m"),
    "intraday_mtf_v2": ("1h", "15m", "3m"),
    "intraday_mtf_v2_pullback_075_v1": ("1h", "15m", "3m"),
    "intraday_mtf_v2_trend70_v1": ("1h", "15m", "3m"),
    "intraday_mtf_v2_cooldown10_v1": ("1h", "15m", "3m"),
}
STRATEGY_SUPPLEMENTAL_TIMEFRAMES = {
    "trend_pullback_v1": ("3m",),
    "trend_pullback_pullback_085_v1": ("3m",),
    "trend_pullback_trend70_v1": ("3m",),
    "trend_pullback_aux2_v1": ("3m",),
    "swing_trend_v1": (),
    "swing_breakout_v1_btc": (),
    "swing_breakout_setup_proximity_045_v1_btc": (),
    "swing_breakout_trigger_buffer_004_v1_btc": (),
    "swing_breakout_base_width_45_v1_btc": (),
    "swing_range_failure_v1_btc": (),
    "swing_range_failure_edge_035_v1_btc": (),
    "swing_range_failure_sweep_008_v1_btc": (),
    "swing_range_failure_max_width_45_v1_btc": (),
    "swing_exhaustion_divergence_ct_block80_v1_btc": (),
    "swing_exhaustion_divergence_min_level3_v1_btc": (),
    "swing_exhaustion_divergence_v1_btc": (),
    "swing_exhaustion_divergence_short_only_v1_btc": (),
    "swing_neutral_range_reversion_v1_btc": (),
    "swing_neutral_range_reversion_edge_030_v1_btc": (),
    "swing_neutral_range_reversion_sweep_008_v1_btc": (),
    "swing_neutral_range_reversion_opp_r_100_v1_btc": (),
    "swing_trend_divergence_v1": (),
    "swing_trend_divergence_min_level3_v1": (),
    "swing_trend_divergence_no_reversal_v1": (),
    "swing_trend_long_divergence_gate_v1": (),
    "swing_trend_long_regime_gate_v1": (),
    "swing_trend_axis_band_diagnostic_v1": (),
    "swing_trend_axis_band_risk_overlay_v1": (),
    "swing_trend_axis_band_state_note_v1": (),
    "swing_trend_confluence_setup_v1": (),
    "swing_trend_confluence_min_hits_3_v1": (),
    "swing_trend_confluence_max_spread_10_v1": (),
    "swing_trend_structure_gate_hard_v1": (),
    "swing_trend_confluence_structure_gate_hard_v1": (),
    "swing_trend_level_aware_confirmation_v1": (),
    "swing_trend_level_aware_confirmation_min_hits_2_v1": (),
    "swing_trend_level_aware_confirmation_ema55_025_v1": (),
    "swing_trend_level_aware_confirmation_band_touch_035_v1": (),
    "swing_trend_matrix_no_gate_current_entry_v1": (),
    "swing_trend_matrix_gate_simple_entry_v1": (),
    "swing_trend_matrix_no_gate_simple_entry_v1": (),
    "swing_trend_long_regime_short_relaxed_trigger_v1": (),
    "swing_trend_long_regime_short90_free_space_v1": (),
    "swing_trend_long_regime_short_no_auxiliary_v1": (),
    "swing_trend_long_regime_short_no_reversal_v1": (),
    "swing_trend_long_regime_short_no_reversal_no_aux_v1": (),
    "swing_trend_ablation_no_reversal_v1": (),
    "swing_trend_ablation_symmetric_regime_v1": (),
    "swing_trend_ablation_no_regained_fast_v1": (),
    "swing_trend_ablation_no_held_slow_v1": (),
    "swing_trend_ablation_no_auxiliary_v1": (),
    "swing_trend_ablation_minimal_trigger_v1": (),
    "swing_trend_simple_candidate_v1": (),
    "swing_trend_simple_candidate_v2": (),
    "trend_following_v1": (),
    "swing_improved_v1": (),
    "mean_reversion_v1": (),
    "intraday_mtf_v1": (),
    "intraday_mtf_v2": (),
    "intraday_mtf_v2_pullback_075_v1": (),
    "intraday_mtf_v2_trend70_v1": (),
    "intraday_mtf_v2_cooldown10_v1": (),
}
STRATEGY_FETCH_TIMEFRAMES = {
    "trend_pullback_v1": ("1d", "4h", "1h", "15m", "3m"),
    "trend_pullback_pullback_085_v1": ("1d", "4h", "1h", "15m", "3m"),
    "trend_pullback_trend70_v1": ("1d", "4h", "1h", "15m", "3m"),
    "trend_pullback_aux2_v1": ("1d", "4h", "1h", "15m", "3m"),
    "swing_trend_v1": ("1d", "4h", "1h"),
    "swing_breakout_v1_btc": ("1d", "4h", "1h"),
    "swing_breakout_setup_proximity_045_v1_btc": ("1d", "4h", "1h"),
    "swing_breakout_trigger_buffer_004_v1_btc": ("1d", "4h", "1h"),
    "swing_breakout_base_width_45_v1_btc": ("1d", "4h", "1h"),
    "swing_range_failure_v1_btc": ("1d", "4h", "1h"),
    "swing_range_failure_edge_035_v1_btc": ("1d", "4h", "1h"),
    "swing_range_failure_sweep_008_v1_btc": ("1d", "4h", "1h"),
    "swing_range_failure_max_width_45_v1_btc": ("1d", "4h", "1h"),
    "swing_exhaustion_divergence_ct_block80_v1_btc": ("1d", "4h", "1h"),
    "swing_exhaustion_divergence_min_level3_v1_btc": ("1d", "4h", "1h"),
    "swing_exhaustion_divergence_v1_btc": ("1d", "4h", "1h"),
    "swing_exhaustion_divergence_short_only_v1_btc": ("1d", "4h", "1h"),
    "swing_neutral_range_reversion_v1_btc": ("1d", "4h", "1h"),
    "swing_neutral_range_reversion_edge_030_v1_btc": ("1d", "4h", "1h"),
    "swing_neutral_range_reversion_sweep_008_v1_btc": ("1d", "4h", "1h"),
    "swing_neutral_range_reversion_opp_r_100_v1_btc": ("1d", "4h", "1h"),
    "swing_trend_divergence_v1": ("1d", "4h", "1h"),
    "swing_trend_divergence_min_level3_v1": ("1d", "4h", "1h"),
    "swing_trend_divergence_no_reversal_v1": ("1d", "4h", "1h"),
    "swing_trend_long_divergence_gate_v1": ("1d", "4h", "1h"),
    "swing_trend_long_regime_gate_v1": ("1d", "4h", "1h"),
    "swing_trend_axis_band_diagnostic_v1": ("1d", "4h", "1h"),
    "swing_trend_axis_band_risk_overlay_v1": ("1d", "4h", "1h"),
    "swing_trend_axis_band_state_note_v1": ("1d", "4h", "1h"),
    "swing_trend_confluence_setup_v1": ("1d", "4h", "1h"),
    "swing_trend_confluence_min_hits_3_v1": ("1d", "4h", "1h"),
    "swing_trend_confluence_max_spread_10_v1": ("1d", "4h", "1h"),
    "swing_trend_structure_gate_hard_v1": ("1d", "4h", "1h"),
    "swing_trend_confluence_structure_gate_hard_v1": ("1d", "4h", "1h"),
    "swing_trend_level_aware_confirmation_v1": ("1d", "4h", "1h"),
    "swing_trend_level_aware_confirmation_min_hits_2_v1": ("1d", "4h", "1h"),
    "swing_trend_level_aware_confirmation_ema55_025_v1": ("1d", "4h", "1h"),
    "swing_trend_level_aware_confirmation_band_touch_035_v1": ("1d", "4h", "1h"),
    "swing_trend_matrix_no_gate_current_entry_v1": ("1d", "4h", "1h"),
    "swing_trend_matrix_gate_simple_entry_v1": ("1d", "4h", "1h"),
    "swing_trend_matrix_no_gate_simple_entry_v1": ("1d", "4h", "1h"),
    "swing_trend_long_regime_short_relaxed_trigger_v1": ("1d", "4h", "1h"),
    "swing_trend_long_regime_short90_free_space_v1": ("1d", "4h", "1h"),
    "swing_trend_long_regime_short_no_auxiliary_v1": ("1d", "4h", "1h"),
    "swing_trend_long_regime_short_no_reversal_v1": ("1d", "4h", "1h"),
    "swing_trend_long_regime_short_no_reversal_no_aux_v1": ("1d", "4h", "1h"),
    "swing_trend_ablation_no_reversal_v1": ("1d", "4h", "1h"),
    "swing_trend_ablation_symmetric_regime_v1": ("1d", "4h", "1h"),
    "swing_trend_ablation_no_regained_fast_v1": ("1d", "4h", "1h"),
    "swing_trend_ablation_no_held_slow_v1": ("1d", "4h", "1h"),
    "swing_trend_ablation_no_auxiliary_v1": ("1d", "4h", "1h"),
    "swing_trend_ablation_minimal_trigger_v1": ("1d", "4h", "1h"),
    "swing_trend_simple_candidate_v1": ("1d", "4h", "1h"),
    "swing_trend_simple_candidate_v2": ("1d", "4h", "1h"),
    "trend_following_v1": ("1d", "4h", "1h"),
    "swing_improved_v1": ("1d", "4h", "1h"),
    "mean_reversion_v1": ("1d", "4h", "1h"),
    "intraday_mtf_v1": ("1h", "15m", "3m"),
    "intraday_mtf_v2": ("1h", "15m", "3m"),
    "intraday_mtf_v2_pullback_075_v1": ("1h", "15m", "3m"),
    "intraday_mtf_v2_trend70_v1": ("1h", "15m", "3m"),
    "intraday_mtf_v2_cooldown10_v1": ("1h", "15m", "3m"),
}


def sort_timeframes(timeframes: list[str]) -> list[str]:
    return sorted(timeframes, key=lambda item: TIMEFRAME_TO_MINUTES[item], reverse=True)


def normalize_timeframes(timeframes: list[str]) -> list[str]:
    lowered = [item.lower() for item in timeframes]
    invalid = [item for item in lowered if item not in SUPPORTED_TIMEFRAMES]
    if invalid:
        raise UnsupportedTimeframeError(f"Unsupported timeframe(s): {', '.join(invalid)}")
    unique = list(dict.fromkeys(lowered))
    return sort_timeframes(unique)


def validate_required_timeframes(strategy_name: str, timeframes: list[str]) -> None:
    if strategy_name not in STRATEGY_REQUIRED_TIMEFRAMES:
        raise UnsupportedTimeframeError(f"Unsupported strategy profile: {strategy_name}")
    required = set(STRATEGY_REQUIRED_TIMEFRAMES.get(strategy_name, ()))
    provided = set(timeframes)
    missing = sorted(required - provided, key=lambda item: TIMEFRAME_TO_MINUTES[item], reverse=True)
    if missing:
        raise UnsupportedTimeframeError(
            f"Strategy '{strategy_name}' requires timeframes: {', '.join(missing)}"
        )


def get_strategy_fetch_timeframes(strategy_name: str) -> tuple[str, ...]:
    if strategy_name not in STRATEGY_FETCH_TIMEFRAMES:
        raise UnsupportedTimeframeError(f"Unsupported strategy profile: {strategy_name}")
    return STRATEGY_FETCH_TIMEFRAMES[strategy_name]


def get_strategy_required_timeframes(strategy_name: str) -> tuple[str, ...]:
    if strategy_name not in STRATEGY_REQUIRED_TIMEFRAMES:
        raise UnsupportedTimeframeError(f"Unsupported strategy profile: {strategy_name}")
    return STRATEGY_REQUIRED_TIMEFRAMES[strategy_name]


def get_strategy_supplemental_timeframes(strategy_name: str) -> tuple[str, ...]:
    if strategy_name not in STRATEGY_SUPPLEMENTAL_TIMEFRAMES:
        raise UnsupportedTimeframeError(f"Unsupported strategy profile: {strategy_name}")
    return STRATEGY_SUPPLEMENTAL_TIMEFRAMES[strategy_name]
